#ifndef JSONTWO_FILEHANDLERINTERNAL_H
#define JSONTWO_FILEHANDLERINTERNAL_H

extern const char* CHANNEL_MAP_JSON;
extern const char* VMX_CHANNELS_JSON;
extern const char* VMX_ENUM_JSON;

#endif //JSONTWO_FILEHANDLERINTERNAL_H
